openapi: 3.0.3
info:
  description: 'This spec describes the context server api as part of NGSI-LD'
  version: latest
  title: NGSI-LD Context Server API
  contact:
    email: stefan.wiedemann@fiware.org
externalDocs:
  description: Find out more about the ETSI ISG Context Information Management
  url: 'https://portal.etsi.org/tb.aspx?tbid=854&SubTB=854'
tags:
  - name: ContextServer
    description: Context server, serving NGSI-LD context.
paths:
  '/jsonldContexts':
    post:
      tags:
        - ContextServer
      description: Create a new context.
      operationId: createContext
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LdContext'
      responses:
        '201':
          description: Created. Contains the resource URI of the created context
          headers:
            Location:
              schema:
                type: string
                format: uri
              description: Id of the created context.
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
    get:
      tags:
        - ContextServer
      description: Get a list of all available contexts.
      operationId: getContextList
      responses:
        '200':
          description: A list of urls for the given contexts.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ContextList'
  '/jsonldContexts/{contextId}':
    get:
      tags:
        - ContextServer
      description: Get the requested context.
      operationId: getContextById
      parameters:
        - $ref: '#/components/parameters/contextId'
      responses:
        '200':
          description: The requested context.
          headers:
            Cache-Control:
              schema:
                $ref: '#/components/headers/Cache-Control'
          content:
            application/ld+json:
              schema:
                $ref: '#/components/schemas/LdContext'
        '404':
          description: No such context exists in the server.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
    post:
      tags:
        - ContextServer
      description: Create a context with the given name.
      operationId: createContextWithId
      parameters:
        - $ref: '#/components/parameters/contextId'
      requestBody:
        required: true
        content:
          application/ld+json:
            schema:
              $ref: '#/components/schemas/LdContext'
      responses:
        '201':
          description: Created. Contains the resource URI of the created context
          headers:
            Location:
              schema:
                type: string
                format: uri
              description: Id of the created context.
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
        '409':
          description: Already exists
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
    delete:
      tags:
        - ContextServer
      description: Delete the requested context.
      operationId: deleteContextById
      parameters:
        - $ref: '#/components/parameters/contextId'
      responses:
        '204':
          description: The requested context was deleted.
        '404':
          description: No such context exists in the server.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'

components:
  headers:
    Cache-Control:
      schema:
        type: string
        default: "max-age=31536000"

  parameters:
    contextId:
      name: contextId
      in: path
      required: true
      schema:
        type: string

  schemas:
    LdContext:
      type: object
    ProblemDetails:
      type: object
      properties:
        type:
          type: string
          format: uri
        title:
          type: string
        detail:
          type: string
      required:
        - type
    ContextList:
      type: array
      items:
        type: string
        format: uri
      minItems: 1